version: 0.2

phases:
  pre_build:
    commands:
      - source /opt/python/run/venv/bin/activate && python -m pip install -r requirements.txt
  build:
    commands:
      
artifacts:
  files:
    - '**/*'