version: 0.2

phases:
  pre_build:
    commands:
      - pip install pipenv
      - pipenv install
      - pipenv run pip install -r requirements.txt
  build:
    commands:
      
artifacts:
  files:
    - '**/*'